artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: andrewmvd/bone-marrow-cell-classification
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  train_data_dir: artifacts/data_ingestion/train_data
  val_data_dir: artifacts/data_ingestion/val_data

